'use client';
import React from "react";

const svgSamples = [
  {
    name: "Colorful Abstract Wave",
    svg: `
      <svg width="320" height="120" viewBox="0 0 320 120" fill="none" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="waveGradient" x1="0" y1="0" x2="320" y2="120" gradientUnits="userSpaceOnUse">
            <stop stop-color="#526CFE"/>
            <stop offset="1" stop-color="#F64F59"/>
          </linearGradient>
        </defs>
        <path d="M0 100 Q 80 20, 160 60 T 320 60 V120 H0Z" fill="url(#waveGradient)"/>
        <circle cx="260" cy="40" r="16" fill="#FFD600" opacity="0.8"/>
        <circle cx="80" cy="30" r="12" fill="#4051B5" opacity="0.7"/>
      </svg>
    `
  },
  {
    name: "Stylized Trail Map",
    svg: `
      <svg width="320" height="180" viewBox="0 0 320 180" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="40" cy="140" r="20" fill="#7BC67E"/>
        <circle cx="280" cy="50" r="20" fill="#F64F59"/>
        <path d="M40 140 Q 90 90, 160 110 Q 230 130, 280 50" stroke="#526CFE" stroke-width="8" fill="none" stroke-linecap="round"/>
        <circle cx="160" cy="110" r="12" fill="#FFD600" stroke="#526CFE" stroke-width="4"/>
        <rect x="120" y="50" width="40" height="18" rx="8" fill="#4051B5"/>
        <text x="128" y="64" fill="#fff" font-size="12" font-family="Inter, sans-serif">Midpoint</text>
      </svg>
    `
  },
  {
    name: "Animated Spinner",
    svg: `
      <svg width="80" height="80" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
        <circle cx="40" cy="40" r="36" fill="none" stroke="#4051B5" stroke-width="8" opacity="0.2"/>
        <path d="M40 4 a36 36 0 0 1 0 72 a36 36 0 0 1 0 -72" fill="none" stroke="#526CFE" stroke-width="8" stroke-linecap="round">
          <animateTransform attributeName="transform" type="rotate" from="0 40 40" to="360 40 40" dur="1.5s" repeatCount="indefinite"/>
        </path>
      </svg>
    `
  },
  {
    name: "Flowchart Example",
    svg: `
      <svg width="340" height="140" xmlns="http://www.w3.org/2000/svg">
        <rect x="20" y="40" width="80" height="40" rx="8" fill="#526CFE"/>
        <text x="60" y="65" fill="#fff" font-size="16" text-anchor="middle" font-family="Inter, sans-serif">Start</text>
        <rect x="130" y="40" width="80" height="40" rx="8" fill="#FFD600"/>
        <text x="170" y="65" fill="#4051B5" font-size="16" text-anchor="middle" font-family="Inter, sans-serif">Step 1</text>
        <rect x="240" y="40" width="80" height="40" rx="8" fill="#F64F59"/>
        <text x="280" y="65" fill="#fff" font-size="16" text-anchor="middle" font-family="Inter, sans-serif">End</text>
        <path d="M100 60 L130 60" stroke="#526CFE" stroke-width="3" marker-end="url(#arrow)"/>
        <path d="M210 60 L240 60" stroke="#FFD600" stroke-width="3" marker-end="url(#arrow2)"/>
        <defs>
          <marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto">
            <polygon points="0 0, 10 3, 0 6" fill="#526CFE"/>
          </marker>
          <marker id="arrow2" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto">
            <polygon points="0 0, 10 3, 0 6" fill="#FFD600"/>
          </marker>
        </defs>
      </svg>
    `
  },
  {
    name: "Pie Chart Example",
    svg: `
      <svg width="160" height="160" viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg">
        <circle r="64" cx="80" cy="80" fill="#f2f2f2"/>
        <path d="M80 80 L80 16 A64 64 0 0 1 144 80 Z" fill="#526CFE"/>
        <path d="M80 80 L144 80 A64 64 0 0 1 112 137.25 Z" fill="#FFD600"/>
        <path d="M80 80 L112 137.25 A64 64 0 0 1 80 144 Z" fill="#F64F59"/>
        <text x="50" y="45" font-size="14" fill="#526CFE">40%</text>
        <text x="120" y="100" font-size="14" fill="#FFD600">35%</text>
        <text x="85" y="150" font-size="14" fill="#F64F59">25%</text>
      </svg>
    `
  }
];

export default function SvgShowcasePage() {
  return (
    <main style={{ maxWidth: 700, margin: "2rem auto", padding: "2rem" }}>
      <h1 style={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, fontSize: '2rem', marginBottom: '1.5rem' }}>SVG Showcase Playground</h1>
      <p style={{ fontSize: '1.1rem', color: '#444', marginBottom: '2rem' }}>
        Below are complex SVGs generated by ChatGPT. Copy, tweak, or inspect their code!
      </p>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', alignItems: 'start' }}>
        {svgSamples.map(({ name, svg }) => (
          <div key={name} style={{ background: '#f5f5f5', borderRadius: 12, padding: '1.5rem', boxShadow: '0 2px 8px #0001' }}>
            <div dangerouslySetInnerHTML={{ __html: svg }} />
            <div style={{ marginTop: '1rem', fontWeight: 600 }}>{name}</div>
            <pre style={{ background: '#222', color: '#fff', borderRadius: 6, padding: '0.5rem', fontSize: 12, overflowX: 'auto', marginTop: 8 }}>{svg.trim()}</pre>
          </div>
        ))}
      </div>
    </main>
  );
}
